// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TempleOfNeah.Sync.Data.Context;

#nullable disable

namespace TempleOfNeah.Sync.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cardanoindexer")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Argus.Sync.Data.Models.ReducerState", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LatestIntersectionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StartIntersectionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("ReducerStates", "cardanoindexer");
                });

            modelBuilder.Entity("TempleOfNeah.Sync.Data.Models.BalanceByAddress", b =>
                {
                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.HasKey("Address");

                    b.ToTable("BalanceByAddress", "cardanoindexer");
                });

            modelBuilder.Entity("TempleOfNeah.Sync.Data.Models.NftInfo", b =>
                {
                    b.Property<string>("PolicyId")
                        .HasColumnType("text");

                    b.Property<string>("AssetName")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Slot")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("PolicyId", "AssetName");

                    b.HasIndex("PolicyId");

                    b.ToTable("NftInfo", "cardanoindexer");
                });

            modelBuilder.Entity("TempleOfNeah.Sync.Data.Models.UtxoByAddress", b =>
                {
                    b.Property<string>("TxHash")
                        .HasColumnType("text");

                    b.Property<long>("OutputIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("Slot")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("SpentAtSlot")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("TxHash", "OutputIndex");

                    b.HasIndex("Address");

                    b.ToTable("UtxoByAddress", "cardanoindexer");
                });
#pragma warning restore 612, 618
        }
    }
}
